// Code generated by generator; DO NOT EDIT.
package holiday

// Init2010 initializes the holiday data for year 2010
func Init2010() map[string]Day {
	data := make(map[string]Day, 37)
	data["2010-01-01"] = Day{Name: "元旦", Date: "2010-01-01", IsOffDay: true}
	data["2010-01-02"] = Day{Name: "元旦", Date: "2010-01-02", IsOffDay: true}
	data["2010-01-03"] = Day{Name: "元旦", Date: "2010-01-03", IsOffDay: true}
	data["2010-02-13"] = Day{Name: "春节", Date: "2010-02-13", IsOffDay: true}
	data["2010-02-14"] = Day{Name: "春节", Date: "2010-02-14", IsOffDay: true}
	data["2010-02-15"] = Day{Name: "春节", Date: "2010-02-15", IsOffDay: true}
	data["2010-02-16"] = Day{Name: "春节", Date: "2010-02-16", IsOffDay: true}
	data["2010-02-17"] = Day{Name: "春节", Date: "2010-02-17", IsOffDay: true}
	data["2010-02-18"] = Day{Name: "春节", Date: "2010-02-18", IsOffDay: true}
	data["2010-02-19"] = Day{Name: "春节", Date: "2010-02-19", IsOffDay: true}
	data["2010-02-20"] = Day{Name: "春节", Date: "2010-02-20", IsOffDay: false}
	data["2010-02-21"] = Day{Name: "春节", Date: "2010-02-21", IsOffDay: false}
	data["2010-04-03"] = Day{Name: "清明节", Date: "2010-04-03", IsOffDay: true}
	data["2010-04-04"] = Day{Name: "清明节", Date: "2010-04-04", IsOffDay: true}
	data["2010-04-05"] = Day{Name: "清明节", Date: "2010-04-05", IsOffDay: true}
	data["2010-05-01"] = Day{Name: "劳动节", Date: "2010-05-01", IsOffDay: true}
	data["2010-05-02"] = Day{Name: "劳动节", Date: "2010-05-02", IsOffDay: true}
	data["2010-05-03"] = Day{Name: "劳动节", Date: "2010-05-03", IsOffDay: true}
	data["2010-06-12"] = Day{Name: "端午节", Date: "2010-06-12", IsOffDay: false}
	data["2010-06-13"] = Day{Name: "端午节", Date: "2010-06-13", IsOffDay: false}
	data["2010-06-14"] = Day{Name: "端午节", Date: "2010-06-14", IsOffDay: true}
	data["2010-06-15"] = Day{Name: "端午节", Date: "2010-06-15", IsOffDay: true}
	data["2010-06-16"] = Day{Name: "端午节", Date: "2010-06-16", IsOffDay: true}
	data["2010-09-19"] = Day{Name: "中秋节", Date: "2010-09-19", IsOffDay: false}
	data["2010-09-22"] = Day{Name: "中秋节", Date: "2010-09-22", IsOffDay: true}
	data["2010-09-23"] = Day{Name: "中秋节", Date: "2010-09-23", IsOffDay: true}
	data["2010-09-24"] = Day{Name: "中秋节", Date: "2010-09-24", IsOffDay: true}
	data["2010-09-25"] = Day{Name: "中秋节", Date: "2010-09-25", IsOffDay: false}
	data["2010-09-26"] = Day{Name: "国庆节", Date: "2010-09-26", IsOffDay: false}
	data["2010-10-01"] = Day{Name: "国庆节", Date: "2010-10-01", IsOffDay: true}
	data["2010-10-02"] = Day{Name: "国庆节", Date: "2010-10-02", IsOffDay: true}
	data["2010-10-03"] = Day{Name: "国庆节", Date: "2010-10-03", IsOffDay: true}
	data["2010-10-04"] = Day{Name: "国庆节", Date: "2010-10-04", IsOffDay: true}
	data["2010-10-05"] = Day{Name: "国庆节", Date: "2010-10-05", IsOffDay: true}
	data["2010-10-06"] = Day{Name: "国庆节", Date: "2010-10-06", IsOffDay: true}
	data["2010-10-07"] = Day{Name: "国庆节", Date: "2010-10-07", IsOffDay: true}
	data["2010-10-09"] = Day{Name: "国庆节", Date: "2010-10-09", IsOffDay: false}
	return data
}

// IsHoliday2010 checks if a given date in 2010 is a holiday
func IsHoliday2010(dateStr string) (bool, string, error) {
	data := GetYearData(2010)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}