// Code generated by generator; DO NOT EDIT.
package holiday

// Init2014 initializes the holiday data for year 2014
func Init2014() map[string]Day {
	data := make(map[string]Day, 27)
	data["2014-01-01"] = Day{Name: "元旦", Date: "2014-01-01", IsOffDay: true}
	data["2014-01-26"] = Day{Name: "春节", Date: "2014-01-26", IsOffDay: false}
	data["2014-01-31"] = Day{Name: "春节", Date: "2014-01-31", IsOffDay: true}
	data["2014-02-01"] = Day{Name: "春节", Date: "2014-02-01", IsOffDay: true}
	data["2014-02-02"] = Day{Name: "春节", Date: "2014-02-02", IsOffDay: true}
	data["2014-02-03"] = Day{Name: "春节", Date: "2014-02-03", IsOffDay: true}
	data["2014-02-04"] = Day{Name: "春节", Date: "2014-02-04", IsOffDay: true}
	data["2014-02-05"] = Day{Name: "春节", Date: "2014-02-05", IsOffDay: true}
	data["2014-02-06"] = Day{Name: "春节", Date: "2014-02-06", IsOffDay: true}
	data["2014-02-08"] = Day{Name: "春节", Date: "2014-02-08", IsOffDay: false}
	data["2014-04-05"] = Day{Name: "清明节", Date: "2014-04-05", IsOffDay: true}
	data["2014-04-07"] = Day{Name: "清明节", Date: "2014-04-07", IsOffDay: true}
	data["2014-05-01"] = Day{Name: "劳动节", Date: "2014-05-01", IsOffDay: true}
	data["2014-05-02"] = Day{Name: "劳动节", Date: "2014-05-02", IsOffDay: true}
	data["2014-05-03"] = Day{Name: "劳动节", Date: "2014-05-03", IsOffDay: true}
	data["2014-05-04"] = Day{Name: "劳动节", Date: "2014-05-04", IsOffDay: false}
	data["2014-06-02"] = Day{Name: "端午节", Date: "2014-06-02", IsOffDay: true}
	data["2014-09-08"] = Day{Name: "中秋节", Date: "2014-09-08", IsOffDay: true}
	data["2014-09-28"] = Day{Name: "国庆节", Date: "2014-09-28", IsOffDay: false}
	data["2014-10-01"] = Day{Name: "国庆节", Date: "2014-10-01", IsOffDay: true}
	data["2014-10-02"] = Day{Name: "国庆节", Date: "2014-10-02", IsOffDay: true}
	data["2014-10-03"] = Day{Name: "国庆节", Date: "2014-10-03", IsOffDay: true}
	data["2014-10-04"] = Day{Name: "国庆节", Date: "2014-10-04", IsOffDay: true}
	data["2014-10-05"] = Day{Name: "国庆节", Date: "2014-10-05", IsOffDay: true}
	data["2014-10-06"] = Day{Name: "国庆节", Date: "2014-10-06", IsOffDay: true}
	data["2014-10-07"] = Day{Name: "国庆节", Date: "2014-10-07", IsOffDay: true}
	data["2014-10-11"] = Day{Name: "国庆节", Date: "2014-10-11", IsOffDay: false}
	return data
}

// IsHoliday2014 checks if a given date in 2014 is a holiday
func IsHoliday2014(dateStr string) (bool, string, error) {
	data := GetYearData(2014)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}