// Code generated by generator; DO NOT EDIT.
package holiday

// Init2012 initializes the holiday data for year 2012
func Init2012() map[string]Day {
	data := make(map[string]Day, 34)
	data["2011-12-31"] = Day{Name: "元旦", Date: "2011-12-31", IsOffDay: false}
	data["2012-01-01"] = Day{Name: "元旦", Date: "2012-01-01", IsOffDay: true}
	data["2012-01-02"] = Day{Name: "元旦", Date: "2012-01-02", IsOffDay: true}
	data["2012-01-03"] = Day{Name: "元旦", Date: "2012-01-03", IsOffDay: true}
	data["2012-01-21"] = Day{Name: "春节", Date: "2012-01-21", IsOffDay: false}
	data["2012-01-22"] = Day{Name: "春节", Date: "2012-01-22", IsOffDay: true}
	data["2012-01-23"] = Day{Name: "春节", Date: "2012-01-23", IsOffDay: true}
	data["2012-01-24"] = Day{Name: "春节", Date: "2012-01-24", IsOffDay: true}
	data["2012-01-25"] = Day{Name: "春节", Date: "2012-01-25", IsOffDay: true}
	data["2012-01-26"] = Day{Name: "春节", Date: "2012-01-26", IsOffDay: true}
	data["2012-01-27"] = Day{Name: "春节", Date: "2012-01-27", IsOffDay: true}
	data["2012-01-28"] = Day{Name: "春节", Date: "2012-01-28", IsOffDay: true}
	data["2012-01-29"] = Day{Name: "春节", Date: "2012-01-29", IsOffDay: false}
	data["2012-03-31"] = Day{Name: "清明节", Date: "2012-03-31", IsOffDay: false}
	data["2012-04-01"] = Day{Name: "清明节", Date: "2012-04-01", IsOffDay: false}
	data["2012-04-02"] = Day{Name: "清明节", Date: "2012-04-02", IsOffDay: true}
	data["2012-04-03"] = Day{Name: "清明节", Date: "2012-04-03", IsOffDay: true}
	data["2012-04-04"] = Day{Name: "清明节", Date: "2012-04-04", IsOffDay: true}
	data["2012-04-28"] = Day{Name: "劳动节", Date: "2012-04-28", IsOffDay: false}
	data["2012-04-29"] = Day{Name: "劳动节", Date: "2012-04-29", IsOffDay: true}
	data["2012-04-30"] = Day{Name: "劳动节", Date: "2012-04-30", IsOffDay: true}
	data["2012-05-01"] = Day{Name: "劳动节", Date: "2012-05-01", IsOffDay: true}
	data["2012-06-22"] = Day{Name: "端午节", Date: "2012-06-22", IsOffDay: true}
	data["2012-06-23"] = Day{Name: "端午节", Date: "2012-06-23", IsOffDay: true}
	data["2012-06-24"] = Day{Name: "端午节", Date: "2012-06-24", IsOffDay: true}
	data["2012-09-29"] = Day{Name: "中秋节、国庆节", Date: "2012-09-29", IsOffDay: false}
	data["2012-09-30"] = Day{Name: "中秋节、国庆节", Date: "2012-09-30", IsOffDay: true}
	data["2012-10-01"] = Day{Name: "中秋节、国庆节", Date: "2012-10-01", IsOffDay: true}
	data["2012-10-02"] = Day{Name: "中秋节、国庆节", Date: "2012-10-02", IsOffDay: true}
	data["2012-10-03"] = Day{Name: "中秋节、国庆节", Date: "2012-10-03", IsOffDay: true}
	data["2012-10-04"] = Day{Name: "中秋节、国庆节", Date: "2012-10-04", IsOffDay: true}
	data["2012-10-05"] = Day{Name: "中秋节、国庆节", Date: "2012-10-05", IsOffDay: true}
	data["2012-10-06"] = Day{Name: "中秋节、国庆节", Date: "2012-10-06", IsOffDay: true}
	data["2012-10-07"] = Day{Name: "中秋节、国庆节", Date: "2012-10-07", IsOffDay: true}
	return data
}

// IsHoliday2012 checks if a given date in 2012 is a holiday
func IsHoliday2012(dateStr string) (bool, string, error) {
	data := GetYearData(2012)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}