// Code generated by generator; DO NOT EDIT.
package holiday

// Init2016 initializes the holiday data for year 2016
func Init2016() map[string]Day {
	data := make(map[string]Day, 30)
	data["2016-01-01"] = Day{Name: "元旦", Date: "2016-01-01", IsOffDay: true}
	data["2016-02-06"] = Day{Name: "春节", Date: "2016-02-06", IsOffDay: false}
	data["2016-02-07"] = Day{Name: "春节", Date: "2016-02-07", IsOffDay: true}
	data["2016-02-08"] = Day{Name: "春节", Date: "2016-02-08", IsOffDay: true}
	data["2016-02-09"] = Day{Name: "春节", Date: "2016-02-09", IsOffDay: true}
	data["2016-02-10"] = Day{Name: "春节", Date: "2016-02-10", IsOffDay: true}
	data["2016-02-11"] = Day{Name: "春节", Date: "2016-02-11", IsOffDay: true}
	data["2016-02-12"] = Day{Name: "春节", Date: "2016-02-12", IsOffDay: true}
	data["2016-02-13"] = Day{Name: "春节", Date: "2016-02-13", IsOffDay: true}
	data["2016-02-14"] = Day{Name: "春节", Date: "2016-02-14", IsOffDay: false}
	data["2016-04-04"] = Day{Name: "清明节", Date: "2016-04-04", IsOffDay: true}
	data["2016-05-01"] = Day{Name: "劳动节", Date: "2016-05-01", IsOffDay: true}
	data["2016-05-02"] = Day{Name: "劳动节", Date: "2016-05-02", IsOffDay: true}
	data["2016-06-09"] = Day{Name: "端午节", Date: "2016-06-09", IsOffDay: true}
	data["2016-06-10"] = Day{Name: "端午节", Date: "2016-06-10", IsOffDay: true}
	data["2016-06-11"] = Day{Name: "端午节", Date: "2016-06-11", IsOffDay: true}
	data["2016-06-12"] = Day{Name: "端午节", Date: "2016-06-12", IsOffDay: false}
	data["2016-09-15"] = Day{Name: "中秋节", Date: "2016-09-15", IsOffDay: true}
	data["2016-09-16"] = Day{Name: "中秋节", Date: "2016-09-16", IsOffDay: true}
	data["2016-09-17"] = Day{Name: "中秋节", Date: "2016-09-17", IsOffDay: true}
	data["2016-09-18"] = Day{Name: "中秋节", Date: "2016-09-18", IsOffDay: false}
	data["2016-10-01"] = Day{Name: "国庆节", Date: "2016-10-01", IsOffDay: true}
	data["2016-10-02"] = Day{Name: "国庆节", Date: "2016-10-02", IsOffDay: true}
	data["2016-10-03"] = Day{Name: "国庆节", Date: "2016-10-03", IsOffDay: true}
	data["2016-10-04"] = Day{Name: "国庆节", Date: "2016-10-04", IsOffDay: true}
	data["2016-10-05"] = Day{Name: "国庆节", Date: "2016-10-05", IsOffDay: true}
	data["2016-10-06"] = Day{Name: "国庆节", Date: "2016-10-06", IsOffDay: true}
	data["2016-10-07"] = Day{Name: "国庆节", Date: "2016-10-07", IsOffDay: true}
	data["2016-10-08"] = Day{Name: "国庆节", Date: "2016-10-08", IsOffDay: false}
	data["2016-10-09"] = Day{Name: "国庆节", Date: "2016-10-09", IsOffDay: false}
	return data
}

// IsHoliday2016 checks if a given date in 2016 is a holiday
func IsHoliday2016(dateStr string) (bool, string, error) {
	data := GetYearData(2016)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}