// Code generated by generator; DO NOT EDIT.
package holiday

// Init2025 initializes the holiday data for year 2025
func Init2025() map[string]Day {
	data := make(map[string]Day, 33)
	data["2025-01-01"] = Day{Name: "元旦", Date: "2025-01-01", IsOffDay: true}
	data["2025-01-26"] = Day{Name: "春节", Date: "2025-01-26", IsOffDay: false}
	data["2025-01-28"] = Day{Name: "春节", Date: "2025-01-28", IsOffDay: true}
	data["2025-01-29"] = Day{Name: "春节", Date: "2025-01-29", IsOffDay: true}
	data["2025-01-30"] = Day{Name: "春节", Date: "2025-01-30", IsOffDay: true}
	data["2025-01-31"] = Day{Name: "春节", Date: "2025-01-31", IsOffDay: true}
	data["2025-02-01"] = Day{Name: "春节", Date: "2025-02-01", IsOffDay: true}
	data["2025-02-02"] = Day{Name: "春节", Date: "2025-02-02", IsOffDay: true}
	data["2025-02-03"] = Day{Name: "春节", Date: "2025-02-03", IsOffDay: true}
	data["2025-02-04"] = Day{Name: "春节", Date: "2025-02-04", IsOffDay: true}
	data["2025-02-08"] = Day{Name: "春节", Date: "2025-02-08", IsOffDay: false}
	data["2025-04-04"] = Day{Name: "清明节", Date: "2025-04-04", IsOffDay: true}
	data["2025-04-05"] = Day{Name: "清明节", Date: "2025-04-05", IsOffDay: true}
	data["2025-04-06"] = Day{Name: "清明节", Date: "2025-04-06", IsOffDay: true}
	data["2025-04-27"] = Day{Name: "劳动节", Date: "2025-04-27", IsOffDay: false}
	data["2025-05-01"] = Day{Name: "劳动节", Date: "2025-05-01", IsOffDay: true}
	data["2025-05-02"] = Day{Name: "劳动节", Date: "2025-05-02", IsOffDay: true}
	data["2025-05-03"] = Day{Name: "劳动节", Date: "2025-05-03", IsOffDay: true}
	data["2025-05-04"] = Day{Name: "劳动节", Date: "2025-05-04", IsOffDay: true}
	data["2025-05-05"] = Day{Name: "劳动节", Date: "2025-05-05", IsOffDay: true}
	data["2025-05-31"] = Day{Name: "端午节", Date: "2025-05-31", IsOffDay: true}
	data["2025-06-01"] = Day{Name: "端午节", Date: "2025-06-01", IsOffDay: true}
	data["2025-06-02"] = Day{Name: "端午节", Date: "2025-06-02", IsOffDay: true}
	data["2025-09-28"] = Day{Name: "国庆节、中秋节", Date: "2025-09-28", IsOffDay: false}
	data["2025-10-01"] = Day{Name: "国庆节、中秋节", Date: "2025-10-01", IsOffDay: true}
	data["2025-10-02"] = Day{Name: "国庆节、中秋节", Date: "2025-10-02", IsOffDay: true}
	data["2025-10-03"] = Day{Name: "国庆节、中秋节", Date: "2025-10-03", IsOffDay: true}
	data["2025-10-04"] = Day{Name: "国庆节、中秋节", Date: "2025-10-04", IsOffDay: true}
	data["2025-10-05"] = Day{Name: "国庆节、中秋节", Date: "2025-10-05", IsOffDay: true}
	data["2025-10-06"] = Day{Name: "国庆节、中秋节", Date: "2025-10-06", IsOffDay: true}
	data["2025-10-07"] = Day{Name: "国庆节、中秋节", Date: "2025-10-07", IsOffDay: true}
	data["2025-10-08"] = Day{Name: "国庆节、中秋节", Date: "2025-10-08", IsOffDay: true}
	data["2025-10-11"] = Day{Name: "国庆节、中秋节", Date: "2025-10-11", IsOffDay: false}
	return data
}

// IsHoliday2025 checks if a given date in 2025 is a holiday
func IsHoliday2025(dateStr string) (bool, string, error) {
	data := GetYearData(2025)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}