// Code generated by generator; DO NOT EDIT.
package holiday

// Init2018 initializes the holiday data for year 2018
func Init2018() map[string]Day {
	data := make(map[string]Day, 29)
	data["2018-01-01"] = Day{Name: "元旦", Date: "2018-01-01", IsOffDay: true}
	data["2018-02-11"] = Day{Name: "春节", Date: "2018-02-11", IsOffDay: false}
	data["2018-02-15"] = Day{Name: "春节", Date: "2018-02-15", IsOffDay: true}
	data["2018-02-16"] = Day{Name: "春节", Date: "2018-02-16", IsOffDay: true}
	data["2018-02-17"] = Day{Name: "春节", Date: "2018-02-17", IsOffDay: true}
	data["2018-02-18"] = Day{Name: "春节", Date: "2018-02-18", IsOffDay: true}
	data["2018-02-19"] = Day{Name: "春节", Date: "2018-02-19", IsOffDay: true}
	data["2018-02-20"] = Day{Name: "春节", Date: "2018-02-20", IsOffDay: true}
	data["2018-02-21"] = Day{Name: "春节", Date: "2018-02-21", IsOffDay: true}
	data["2018-02-24"] = Day{Name: "春节", Date: "2018-02-24", IsOffDay: false}
	data["2018-04-05"] = Day{Name: "清明节", Date: "2018-04-05", IsOffDay: true}
	data["2018-04-06"] = Day{Name: "清明节", Date: "2018-04-06", IsOffDay: true}
	data["2018-04-07"] = Day{Name: "清明节", Date: "2018-04-07", IsOffDay: true}
	data["2018-04-08"] = Day{Name: "清明节", Date: "2018-04-08", IsOffDay: false}
	data["2018-04-28"] = Day{Name: "劳动节", Date: "2018-04-28", IsOffDay: false}
	data["2018-04-29"] = Day{Name: "劳动节", Date: "2018-04-29", IsOffDay: true}
	data["2018-04-30"] = Day{Name: "劳动节", Date: "2018-04-30", IsOffDay: true}
	data["2018-05-01"] = Day{Name: "劳动节", Date: "2018-05-01", IsOffDay: true}
	data["2018-06-18"] = Day{Name: "端午节", Date: "2018-06-18", IsOffDay: true}
	data["2018-09-24"] = Day{Name: "中秋节", Date: "2018-09-24", IsOffDay: true}
	data["2018-09-29"] = Day{Name: "国庆节", Date: "2018-09-29", IsOffDay: false}
	data["2018-09-30"] = Day{Name: "国庆节", Date: "2018-09-30", IsOffDay: false}
	data["2018-10-01"] = Day{Name: "国庆节", Date: "2018-10-01", IsOffDay: true}
	data["2018-10-02"] = Day{Name: "国庆节", Date: "2018-10-02", IsOffDay: true}
	data["2018-10-03"] = Day{Name: "国庆节", Date: "2018-10-03", IsOffDay: true}
	data["2018-10-04"] = Day{Name: "国庆节", Date: "2018-10-04", IsOffDay: true}
	data["2018-10-05"] = Day{Name: "国庆节", Date: "2018-10-05", IsOffDay: true}
	data["2018-10-06"] = Day{Name: "国庆节", Date: "2018-10-06", IsOffDay: true}
	data["2018-10-07"] = Day{Name: "国庆节", Date: "2018-10-07", IsOffDay: true}
	return data
}

// IsHoliday2018 checks if a given date in 2018 is a holiday
func IsHoliday2018(dateStr string) (bool, string, error) {
	data := GetYearData(2018)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}