// Code generated by generator; DO NOT EDIT.
package holiday

// Init2020 initializes the holiday data for year 2020
func Init2020() map[string]Day {
	data := make(map[string]Day, 37)
	data["2020-01-01"] = Day{Name: "元旦", Date: "2020-01-01", IsOffDay: true}
	data["2020-01-19"] = Day{Name: "春节", Date: "2020-01-19", IsOffDay: false}
	data["2020-01-24"] = Day{Name: "春节", Date: "2020-01-24", IsOffDay: true}
	data["2020-01-25"] = Day{Name: "春节", Date: "2020-01-25", IsOffDay: true}
	data["2020-01-26"] = Day{Name: "春节", Date: "2020-01-26", IsOffDay: true}
	data["2020-01-27"] = Day{Name: "春节", Date: "2020-01-27", IsOffDay: true}
	data["2020-01-28"] = Day{Name: "春节", Date: "2020-01-28", IsOffDay: true}
	data["2020-01-29"] = Day{Name: "春节", Date: "2020-01-29", IsOffDay: true}
	data["2020-01-30"] = Day{Name: "春节", Date: "2020-01-30", IsOffDay: true}
	data["2020-01-31"] = Day{Name: "春节", Date: "2020-01-31", IsOffDay: true}
	data["2020-02-01"] = Day{Name: "春节", Date: "2020-02-01", IsOffDay: true}
	data["2020-02-02"] = Day{Name: "春节", Date: "2020-02-02", IsOffDay: true}
	data["2020-02-03"] = Day{Name: "春节", Date: "2020-02-03", IsOffDay: false}
	data["2020-04-04"] = Day{Name: "清明节", Date: "2020-04-04", IsOffDay: true}
	data["2020-04-05"] = Day{Name: "清明节", Date: "2020-04-05", IsOffDay: true}
	data["2020-04-06"] = Day{Name: "清明节", Date: "2020-04-06", IsOffDay: true}
	data["2020-04-26"] = Day{Name: "劳动节", Date: "2020-04-26", IsOffDay: false}
	data["2020-05-01"] = Day{Name: "劳动节", Date: "2020-05-01", IsOffDay: true}
	data["2020-05-02"] = Day{Name: "劳动节", Date: "2020-05-02", IsOffDay: true}
	data["2020-05-03"] = Day{Name: "劳动节", Date: "2020-05-03", IsOffDay: true}
	data["2020-05-04"] = Day{Name: "劳动节", Date: "2020-05-04", IsOffDay: true}
	data["2020-05-05"] = Day{Name: "劳动节", Date: "2020-05-05", IsOffDay: true}
	data["2020-05-09"] = Day{Name: "劳动节", Date: "2020-05-09", IsOffDay: false}
	data["2020-06-25"] = Day{Name: "端午节", Date: "2020-06-25", IsOffDay: true}
	data["2020-06-26"] = Day{Name: "端午节", Date: "2020-06-26", IsOffDay: true}
	data["2020-06-27"] = Day{Name: "端午节", Date: "2020-06-27", IsOffDay: true}
	data["2020-06-28"] = Day{Name: "端午节", Date: "2020-06-28", IsOffDay: false}
	data["2020-09-27"] = Day{Name: "国庆节、中秋节", Date: "2020-09-27", IsOffDay: false}
	data["2020-10-01"] = Day{Name: "国庆节、中秋节", Date: "2020-10-01", IsOffDay: true}
	data["2020-10-02"] = Day{Name: "国庆节、中秋节", Date: "2020-10-02", IsOffDay: true}
	data["2020-10-03"] = Day{Name: "国庆节、中秋节", Date: "2020-10-03", IsOffDay: true}
	data["2020-10-04"] = Day{Name: "国庆节、中秋节", Date: "2020-10-04", IsOffDay: true}
	data["2020-10-05"] = Day{Name: "国庆节、中秋节", Date: "2020-10-05", IsOffDay: true}
	data["2020-10-06"] = Day{Name: "国庆节、中秋节", Date: "2020-10-06", IsOffDay: true}
	data["2020-10-07"] = Day{Name: "国庆节、中秋节", Date: "2020-10-07", IsOffDay: true}
	data["2020-10-08"] = Day{Name: "国庆节、中秋节", Date: "2020-10-08", IsOffDay: true}
	data["2020-10-10"] = Day{Name: "国庆节、中秋节", Date: "2020-10-10", IsOffDay: false}
	return data
}

// IsHoliday2020 checks if a given date in 2020 is a holiday
func IsHoliday2020(dateStr string) (bool, string, error) {
	data := GetYearData(2020)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}