// Code generated by generator; DO NOT EDIT.
package holiday

// Init2027 initializes the holiday data for year 2027
func Init2027() map[string]Day {
	data := make(map[string]Day, 0)
	return data
}

// IsHoliday2027 checks if a given date in 2027 is a holiday
func IsHoliday2027(dateStr string) (bool, string, error) {
	data := GetYearData(2027)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}