// Code generated by generator; DO NOT EDIT.
package holiday

// Init2024 initializes the holiday data for year 2024
func Init2024() map[string]Day {
	data := make(map[string]Day, 36)
	data["2024-01-01"] = Day{Name: "元旦", Date: "2024-01-01", IsOffDay: true}
	data["2024-02-04"] = Day{Name: "春节", Date: "2024-02-04", IsOffDay: false}
	data["2024-02-10"] = Day{Name: "春节", Date: "2024-02-10", IsOffDay: true}
	data["2024-02-11"] = Day{Name: "春节", Date: "2024-02-11", IsOffDay: true}
	data["2024-02-12"] = Day{Name: "春节", Date: "2024-02-12", IsOffDay: true}
	data["2024-02-13"] = Day{Name: "春节", Date: "2024-02-13", IsOffDay: true}
	data["2024-02-14"] = Day{Name: "春节", Date: "2024-02-14", IsOffDay: true}
	data["2024-02-15"] = Day{Name: "春节", Date: "2024-02-15", IsOffDay: true}
	data["2024-02-16"] = Day{Name: "春节", Date: "2024-02-16", IsOffDay: true}
	data["2024-02-17"] = Day{Name: "春节", Date: "2024-02-17", IsOffDay: true}
	data["2024-02-18"] = Day{Name: "春节", Date: "2024-02-18", IsOffDay: false}
	data["2024-04-04"] = Day{Name: "清明节", Date: "2024-04-04", IsOffDay: true}
	data["2024-04-05"] = Day{Name: "清明节", Date: "2024-04-05", IsOffDay: true}
	data["2024-04-06"] = Day{Name: "清明节", Date: "2024-04-06", IsOffDay: true}
	data["2024-04-07"] = Day{Name: "清明节", Date: "2024-04-07", IsOffDay: false}
	data["2024-04-28"] = Day{Name: "劳动节", Date: "2024-04-28", IsOffDay: false}
	data["2024-05-01"] = Day{Name: "劳动节", Date: "2024-05-01", IsOffDay: true}
	data["2024-05-02"] = Day{Name: "劳动节", Date: "2024-05-02", IsOffDay: true}
	data["2024-05-03"] = Day{Name: "劳动节", Date: "2024-05-03", IsOffDay: true}
	data["2024-05-04"] = Day{Name: "劳动节", Date: "2024-05-04", IsOffDay: true}
	data["2024-05-05"] = Day{Name: "劳动节", Date: "2024-05-05", IsOffDay: true}
	data["2024-05-11"] = Day{Name: "劳动节", Date: "2024-05-11", IsOffDay: false}
	data["2024-06-10"] = Day{Name: "端午节", Date: "2024-06-10", IsOffDay: true}
	data["2024-09-14"] = Day{Name: "中秋节", Date: "2024-09-14", IsOffDay: false}
	data["2024-09-15"] = Day{Name: "中秋节", Date: "2024-09-15", IsOffDay: true}
	data["2024-09-16"] = Day{Name: "中秋节", Date: "2024-09-16", IsOffDay: true}
	data["2024-09-17"] = Day{Name: "中秋节", Date: "2024-09-17", IsOffDay: true}
	data["2024-09-29"] = Day{Name: "国庆节", Date: "2024-09-29", IsOffDay: false}
	data["2024-10-01"] = Day{Name: "国庆节", Date: "2024-10-01", IsOffDay: true}
	data["2024-10-02"] = Day{Name: "国庆节", Date: "2024-10-02", IsOffDay: true}
	data["2024-10-03"] = Day{Name: "国庆节", Date: "2024-10-03", IsOffDay: true}
	data["2024-10-04"] = Day{Name: "国庆节", Date: "2024-10-04", IsOffDay: true}
	data["2024-10-05"] = Day{Name: "国庆节", Date: "2024-10-05", IsOffDay: true}
	data["2024-10-06"] = Day{Name: "国庆节", Date: "2024-10-06", IsOffDay: true}
	data["2024-10-07"] = Day{Name: "国庆节", Date: "2024-10-07", IsOffDay: true}
	data["2024-10-12"] = Day{Name: "国庆节", Date: "2024-10-12", IsOffDay: false}
	return data
}

// IsHoliday2024 checks if a given date in 2024 is a holiday
func IsHoliday2024(dateStr string) (bool, string, error) {
	data := GetYearData(2024)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}