// Code generated by generator; DO NOT EDIT.
package holiday

// Init2017 initializes the holiday data for year 2017
func Init2017() map[string]Day {
	data := make(map[string]Day, 29)
	data["2017-01-01"] = Day{Name: "元旦", Date: "2017-01-01", IsOffDay: true}
	data["2017-01-02"] = Day{Name: "元旦", Date: "2017-01-02", IsOffDay: true}
	data["2017-01-22"] = Day{Name: "春节", Date: "2017-01-22", IsOffDay: false}
	data["2017-01-27"] = Day{Name: "春节", Date: "2017-01-27", IsOffDay: true}
	data["2017-01-28"] = Day{Name: "春节", Date: "2017-01-28", IsOffDay: true}
	data["2017-01-29"] = Day{Name: "春节", Date: "2017-01-29", IsOffDay: true}
	data["2017-01-30"] = Day{Name: "春节", Date: "2017-01-30", IsOffDay: true}
	data["2017-01-31"] = Day{Name: "春节", Date: "2017-01-31", IsOffDay: true}
	data["2017-02-01"] = Day{Name: "春节", Date: "2017-02-01", IsOffDay: true}
	data["2017-02-02"] = Day{Name: "春节", Date: "2017-02-02", IsOffDay: true}
	data["2017-02-04"] = Day{Name: "春节", Date: "2017-02-04", IsOffDay: false}
	data["2017-04-01"] = Day{Name: "清明节", Date: "2017-04-01", IsOffDay: false}
	data["2017-04-02"] = Day{Name: "清明节", Date: "2017-04-02", IsOffDay: true}
	data["2017-04-03"] = Day{Name: "清明节", Date: "2017-04-03", IsOffDay: true}
	data["2017-04-04"] = Day{Name: "清明节", Date: "2017-04-04", IsOffDay: true}
	data["2017-05-01"] = Day{Name: "劳动节", Date: "2017-05-01", IsOffDay: true}
	data["2017-05-27"] = Day{Name: "端午节", Date: "2017-05-27", IsOffDay: false}
	data["2017-05-28"] = Day{Name: "端午节", Date: "2017-05-28", IsOffDay: true}
	data["2017-05-29"] = Day{Name: "端午节", Date: "2017-05-29", IsOffDay: true}
	data["2017-05-30"] = Day{Name: "端午节", Date: "2017-05-30", IsOffDay: true}
	data["2017-09-30"] = Day{Name: "中秋节、国庆节", Date: "2017-09-30", IsOffDay: false}
	data["2017-10-01"] = Day{Name: "中秋节、国庆节", Date: "2017-10-01", IsOffDay: true}
	data["2017-10-02"] = Day{Name: "中秋节、国庆节", Date: "2017-10-02", IsOffDay: true}
	data["2017-10-03"] = Day{Name: "中秋节、国庆节", Date: "2017-10-03", IsOffDay: true}
	data["2017-10-04"] = Day{Name: "中秋节、国庆节", Date: "2017-10-04", IsOffDay: true}
	data["2017-10-05"] = Day{Name: "中秋节、国庆节", Date: "2017-10-05", IsOffDay: true}
	data["2017-10-06"] = Day{Name: "中秋节、国庆节", Date: "2017-10-06", IsOffDay: true}
	data["2017-10-07"] = Day{Name: "中秋节、国庆节", Date: "2017-10-07", IsOffDay: true}
	data["2017-10-08"] = Day{Name: "中秋节、国庆节", Date: "2017-10-08", IsOffDay: true}
	return data
}

// IsHoliday2017 checks if a given date in 2017 is a holiday
func IsHoliday2017(dateStr string) (bool, string, error) {
	data := GetYearData(2017)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}