// Code generated by generator; DO NOT EDIT.
package holiday

// Init2021 initializes the holiday data for year 2021
func Init2021() map[string]Day {
	data := make(map[string]Day, 38)
	data["2021-01-01"] = Day{Name: "元旦", Date: "2021-01-01", IsOffDay: true}
	data["2021-01-02"] = Day{Name: "元旦", Date: "2021-01-02", IsOffDay: true}
	data["2021-01-03"] = Day{Name: "元旦", Date: "2021-01-03", IsOffDay: true}
	data["2021-02-07"] = Day{Name: "春节", Date: "2021-02-07", IsOffDay: false}
	data["2021-02-11"] = Day{Name: "春节", Date: "2021-02-11", IsOffDay: true}
	data["2021-02-12"] = Day{Name: "春节", Date: "2021-02-12", IsOffDay: true}
	data["2021-02-13"] = Day{Name: "春节", Date: "2021-02-13", IsOffDay: true}
	data["2021-02-14"] = Day{Name: "春节", Date: "2021-02-14", IsOffDay: true}
	data["2021-02-15"] = Day{Name: "春节", Date: "2021-02-15", IsOffDay: true}
	data["2021-02-16"] = Day{Name: "春节", Date: "2021-02-16", IsOffDay: true}
	data["2021-02-17"] = Day{Name: "春节", Date: "2021-02-17", IsOffDay: true}
	data["2021-02-20"] = Day{Name: "春节", Date: "2021-02-20", IsOffDay: false}
	data["2021-04-03"] = Day{Name: "清明节", Date: "2021-04-03", IsOffDay: true}
	data["2021-04-04"] = Day{Name: "清明节", Date: "2021-04-04", IsOffDay: true}
	data["2021-04-05"] = Day{Name: "清明节", Date: "2021-04-05", IsOffDay: true}
	data["2021-04-25"] = Day{Name: "劳动节", Date: "2021-04-25", IsOffDay: false}
	data["2021-05-01"] = Day{Name: "劳动节", Date: "2021-05-01", IsOffDay: true}
	data["2021-05-02"] = Day{Name: "劳动节", Date: "2021-05-02", IsOffDay: true}
	data["2021-05-03"] = Day{Name: "劳动节", Date: "2021-05-03", IsOffDay: true}
	data["2021-05-04"] = Day{Name: "劳动节", Date: "2021-05-04", IsOffDay: true}
	data["2021-05-05"] = Day{Name: "劳动节", Date: "2021-05-05", IsOffDay: true}
	data["2021-05-08"] = Day{Name: "劳动节", Date: "2021-05-08", IsOffDay: false}
	data["2021-06-12"] = Day{Name: "端午节", Date: "2021-06-12", IsOffDay: true}
	data["2021-06-13"] = Day{Name: "端午节", Date: "2021-06-13", IsOffDay: true}
	data["2021-06-14"] = Day{Name: "端午节", Date: "2021-06-14", IsOffDay: true}
	data["2021-09-18"] = Day{Name: "中秋节", Date: "2021-09-18", IsOffDay: false}
	data["2021-09-19"] = Day{Name: "中秋节", Date: "2021-09-19", IsOffDay: true}
	data["2021-09-20"] = Day{Name: "中秋节", Date: "2021-09-20", IsOffDay: true}
	data["2021-09-21"] = Day{Name: "中秋节", Date: "2021-09-21", IsOffDay: true}
	data["2021-09-26"] = Day{Name: "国庆节", Date: "2021-09-26", IsOffDay: false}
	data["2021-10-01"] = Day{Name: "国庆节", Date: "2021-10-01", IsOffDay: true}
	data["2021-10-02"] = Day{Name: "国庆节", Date: "2021-10-02", IsOffDay: true}
	data["2021-10-03"] = Day{Name: "国庆节", Date: "2021-10-03", IsOffDay: true}
	data["2021-10-04"] = Day{Name: "国庆节", Date: "2021-10-04", IsOffDay: true}
	data["2021-10-05"] = Day{Name: "国庆节", Date: "2021-10-05", IsOffDay: true}
	data["2021-10-06"] = Day{Name: "国庆节", Date: "2021-10-06", IsOffDay: true}
	data["2021-10-07"] = Day{Name: "国庆节", Date: "2021-10-07", IsOffDay: true}
	data["2021-10-09"] = Day{Name: "国庆节", Date: "2021-10-09", IsOffDay: false}
	return data
}

// IsHoliday2021 checks if a given date in 2021 is a holiday
func IsHoliday2021(dateStr string) (bool, string, error) {
	data := GetYearData(2021)
	if day, exists := data[dateStr]; exists {
		return day.IsOffDay, day.Name, nil
	}
	return false, "", nil
}